NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [3]:
import numpy as np
zeros_array = np.zeros((4,3), dtype=int)
ones_array = np.ones((3,3), dtype=int)
range_array = np.arange(0, 20, 5)
linspace_array = np.linspace(0, 1, 4)
normal_array = np.random.normal(0, 1, (2,2))

print("크기가 4x3인 모든 값이 0인 배열: \n", zeros_array)
print("크기가 3x3인 모든 값이 1인 배열: \n", ones_array)
print("0에서 20까지 5씩 증가하는 값으로 구성된 배열: \n", range_array)
print("0과 1 사이의 4개의 등간격 값을 가진 배열: \n", linspace_array)
print("크기가 2x2인 정규 분포로 구성된 배열: \n", normal_array)

크기가 4x3인 모든 값이 0인 배열: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
크기가 3x3인 모든 값이 1인 배열: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
0에서 20까지 5씩 증가하는 값으로 구성된 배열: 
 [ 0  5 10 15]
0과 1 사이의 4개의 등간격 값을 가진 배열: 
 [0.         0.33333333 0.66666667 1.        ]
크기가 2x2인 정규 분포로 구성된 배열: 
 [[-1.66531842  0.20521692]
 [-0.05663007  2.00209   ]]


1. 배열 `arr`에서 1번 열만 추출
2. 배열 `arr`에서 1번 행, 2번 열의 값을 출력
3. 배열 `arr`에서 0번 행부터 1번 행까지 선택하고, 0번과 1번 열만 추출

In [12]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[1])
print(arr[1, 2])
print(arr[0:2, 1:3])


[40 50 60]
60
[[20 30]
 [50 60]]


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

In [8]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[[0, 2, 4]])
print(arr[arr > 50])

[10 30 50]
[60 70]


어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

In [11]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])
print(sales[sales > 200])
print(sales[:, 2][sales[:, 2] < 100])
print(sales[sales[:, 1] > 150])

[220 300 320 310]
[70]
[[200 180 220]
 [300 320 310]]


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [13]:
sales1 = np.array([200, 340, 150, 400])
sales2 = np.array([220, 300, 180, 420])
print(sales1 + sales2)
print(sales1.mean())

[420 640 330 820]
272.5


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

In [14]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


다음 두 배열 간의 내적 연산을 수행하세요.

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1.dot(arr2))


32


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.

In [17]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 20])
print(arr.sum(), arr.max(), arr.min(), arr.mean())

[30 40 50]
150 50 10 30.0


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.

In [42]:
import numpy as np

arr = np.array([10, 20, 30, 30, 40, 50, 60])

# 최빈값 (scipy 없이)
values, counts = np.unique(arr, return_counts=True)
mode = values[np.argmax(counts)]

print(f"평균: {arr.mean():.4f}")
print(f"중앙값: {np.median(arr)}")
print(f"최빈값: {mode}")
print(f"분산: {arr.var():.4f}")
print(f"표준편차: {arr.std():.4f}")
print(f"범위: {arr.min()} ~ {arr.max()}")

평균: 34.2857
중앙값: 30.0
최빈값: 30
분산: 253.0612
표준편차: 15.9079
범위: 10 ~ 60


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [25]:
np.random.seed(1234)
normal_dist = np.random.normal(0, 1, 1000)
uniform_dist = np.random.uniform(0, 1, 1000)
print(normal_dist.mean(), normal_dist.std())
print(uniform_dist.mean(), uniform_dist.std())

0.01574058215376203 0.9730661993772295
0.4950416291818855 0.2959548222368978


아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.

In [43]:
import numpy as np

scores_math =    [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]
scores = np.array([scores_math, scores_english, scores_science])

# (3, 10) → (10, 3) : 한 행 = 한 학생의 3과목 점수
scores_T = scores.T

# 각 학생의 3과목 평균 (axis=1: 행 방향) → (10,)
student_avg = scores_T.mean(axis=1)

print("학생별 평균:", student_avg)
print("분산:", student_avg.var())
print("표준편차:", student_avg.std())

학생별 평균: [87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]
분산: 11.89333333333335
표준편차: 3.4486712417006857


다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.

In [27]:
arr = np.array([50, 10, 30, 40, 20])
print(np.sort(arr))
print(np.sort(arr)[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.

In [28]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
print(np.sort(arr2d, axis=0))
print(np.sort(arr2d, axis=1))

[[2 3 1]
 [8 9 5]]
[[3 5 8]
 [1 2 9]]


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.

In [30]:
arr = np.array([15, 10, 20])
print(np.argsort(arr))
print(np.sort(arr))

[1 0 2]
[10 15 20]


다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.

In [31]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


다음 두 개의 2차원 배열을 np.concatenate()와 np.vstack()을 사용하여 각각 병합하세요.

In [32]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.concatenate((arr1, arr2), axis=0))
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

In [36]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])


import numpy as np

fruit_names = np.array(['사과', '바나나', '오렌지'])
months = ['1월', '2월', '3월', '4월', '5월', '6월']

# 1. 각 지점에서 과일별 월별 평균 판매량 (axis=2: 월 방향 평균) → (5, 3)
branch_fruit_avg = sales_data.mean(axis=2)
print("=== 1. 지점별 과일 월평균 판매량 ===")
for i, branch in enumerate(branch_fruit_avg):
    print(f"지점 {i+1}: " + ", ".join(f"{fruit_names[j]} {branch[j]:.1f}" for j in range(3)))

# 2. 각 월마다 전체 지점 합산 후 가장 많이 팔린 과일 (axis=0: 지점 합) → (3, 6)
monthly_fruit_sum = sales_data.sum(axis=0)
print("\n=== 2. 월별 최다 판매 과일 ===")
for m in range(6):
    fruit_idx = np.argmax(monthly_fruit_sum[:, m])
    print(f"{months[m]}: {fruit_names[fruit_idx]} ({monthly_fruit_sum[fruit_idx, m]}개)")

# 3. 과일별 6개월 전체 지점 총 판매량 (지점·월 합) → (3,)
fruit_total = sales_data.sum(axis=(0, 2))
print("\n=== 3. 과일별 총 판매량 ===")
for j in range(3):
    print(f"{fruit_names[j]}: {fruit_total[j]}개")
print(f"→ 최다 판매 과일: {fruit_names[np.argmax(fruit_total)]} ({fruit_total.max()}개)")

# 4. 판매량 150개 이상 데이터 추출
print("\n=== 4. 판매량 150개 이상 데이터 ===")
branch_idx, fruit_idx, month_idx = np.where(sales_data >= 150)
for s, f, m in zip(branch_idx, fruit_idx, month_idx):
    print(f"지점 {s+1} | {fruit_names[f]} | {months[m]} | {sales_data[s, f, m]}개")

=== 1. 지점별 과일 월평균 판매량 ===
지점 1: 사과 181.7, 바나나 156.7, 오렌지 131.7
지점 2: 사과 111.7, 바나나 87.5, 오렌지 85.8
지점 3: 사과 161.7, 바나나 135.0, 오렌지 120.0
지점 4: 사과 148.3, 바나나 112.5, 오렌지 115.0
지점 5: 사과 120.0, 바나나 94.2, 오렌지 90.8

=== 2. 월별 최다 판매 과일 ===
1월: 사과 (520개)
2월: 사과 (620개)
3월: 사과 (750개)
4월: 사과 (860개)
5월: 사과 (760개)
6월: 사과 (830개)

=== 3. 과일별 총 판매량 ===
사과: 4340개
바나나: 3515개
오렌지: 3260개
→ 최다 판매 과일: 사과 (4340개)

=== 4. 판매량 150개 이상 데이터 ===
지점 1 | 사과 | 2월 | 150개
지점 1 | 사과 | 3월 | 200개
지점 1 | 사과 | 4월 | 230개
지점 1 | 사과 | 5월 | 180개
지점 1 | 사과 | 6월 | 210개
지점 1 | 바나나 | 3월 | 170개
지점 1 | 바나나 | 4월 | 190개
지점 1 | 바나나 | 5월 | 160개
지점 1 | 바나나 | 6월 | 180개
지점 1 | 오렌지 | 3월 | 160개
지점 1 | 오렌지 | 6월 | 150개
지점 3 | 사과 | 3월 | 160개
지점 3 | 사과 | 4월 | 180개
지점 3 | 사과 | 5월 | 170개
지점 3 | 사과 | 6월 | 190개
지점 3 | 바나나 | 4월 | 150개
지점 3 | 바나나 | 6월 | 160개
지점 4 | 사과 | 3월 | 150개
지점 4 | 사과 | 4월 | 170개
지점 4 | 사과 | 5월 | 160개
지점 4 | 사과 | 6월 | 180개
